version: '3.9'
services:
  orders:
    container_name: orders
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongodb-primary
      - rabbitmq
      # - mongodb-secondary
      # - mongodb-arbiter
    volumes:
      - .:/urs/src/app
      - /urs/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network
  billing:
    container_name: billing
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - mongodb-primary
      - rabbitmq
      - orders
    volumes:
      - .:/urs/src/app
      - /urs/src/app/node_modules
    networks:
      - app-network
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    hostname: mongodb-primary
    environment:
      # - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      # - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      # - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - 27019:27017
    networks:
      - app-network
  # mongodb-secondary:
  #   image: docker.io/bitnami/mongodb:5.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123
  #   networks:
  #     - app-network
  # mongodb-arbiter:
    # image: docker.io/bitnami/mongodb:5.0
    # depends_on:
    #   - mongodb-primary
    # environment:
    #   - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
    #   - MONGODB_REPLICA_SET_MODE=arbiter
    #   - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
    #   - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
    #   - MONGODB_REPLICA_SET_KEY=replicasetkey123
    # networks:
    #   - app-network
volumes:
  mongodb_master_data:
    driver: local
networks:
    app-network:
      driver: bridge